modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://minecraft.curseforge.com/projects/durability-notifier/issues"

[[mods]]
modId="durabilitynotifier"
version="${file.jarVersion}"
displayName="Durability Notifier"
displayURL="https://minecraft.curseforge.com/projects/durability-notifier"
authors="Mrbysco"
description='''
A minecraft mod that notifies you when your durability gets at a certain percentage
'''

[[dependencies.durabilitynotifier]]
modId="forge"
mandatory=true
versionRange="[25,)"
ordering="NONE"
side="CLIENT"

[[dependencies.durabilitynotifier]]
modId="minecraft"
mandatory=true
versionRange="[1.13.2]"
ordering="NONE"
side="BOTH"